services:
  browser:
    container_name: browser
    restart: always
    build: ./browser
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    network_mode: "host"
    depends_on:
      mysql:
        condition: service_healthy
  p2p:
    container_name: p2p
    restart: always
    build: ./p2p
    environment:
      RELAY_URL: ${RELAY_URL}
    network_mode: "host"
    depends_on:
      - browser
  mysql:
    container_name: mysql
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    network_mode: "host"

volumes:
  mysql: # Docker will create the volume for you in the /var/lib/docker/volumes folder